[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
soflex = "71ocAFn8LQ2AaQ9wfjTUiHAv1QqDVVYuKLNrjpf9vkTb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/harshal0902/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
